# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory_id', models.CharField(max_length=75)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('advisory_number', models.CharField(default=None, max_length=4, null=True)),
                ('storm_location', models.CharField(max_length=40)),
                ('max_sus_wind', models.IntegerField(default=None, null=True)),
                ('speed', models.IntegerField(default=None, null=True)),
                ('min_cent_pressure', models.FloatField(default=None, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Subtropical Depression'), (2, 'Tropical Depression'), (3, 'Tropical Storm'), (4, 'Tropical Cyclone'), (5, 'Hurricane'), (0, 'Remnants Of')])),
                ('current_name', models.CharField(default=None, max_length=40, null=True)),
                ('lat', models.FloatField(default=None, null=True)),
                ('long', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tracker.models.PathAndRename(''))),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=75)),
                ('target', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stormid', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('region', models.CharField(max_length=2)),
                ('annual_cyclone_number', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2017)),
            ],
        ),
        migrations.AddField(
            model_name='advisory',
            name='stormid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Storm'),
        ),
    ]
