# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170731_0338'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storm',
            managers=[
            ],
        ),
    ]
