# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170731_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
