# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_advisory_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='rm',
            field=models.BooleanField(default=False),
        ),
    ]
