# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_advisory_rm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisory',
            name='rm',
        ),
    ]
